
help:
	@echo -e "Welcome to the RTL Encryption makefile"
	@echo -e "USAGE"
	@echo -e "  encrypt - encrypts the files using vencrypt and vhencrypt"

encrypt:
	@encrypt.sh >run.log 2>&1

clean:
	@rm -fr run.log out ; clear
